version: '3.8'

services:
    postgres:
        image: postgres:13
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: my_database
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user_password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: