# This is a comment

[default]
address = "0.0.0.0"
port = 8000
log_level = "normal"
secret_key = "your-secret-key"

[debug]
address = "127.0.0.1"
port = 8000
log_level = "debug"

[release]
address = "0.0.0.0"
port = 8000
log_level = "critical"
secret_key = "your-release-secret-key"

[default.databases]
my_db = { url = "postgres://user:user_password@localhost/my_database" }